version: '3'

tasks:
  fmt:
    cmds:
      - uv run ruff check --fix src workspace
      - uv run ruff check --fix --unsafe-fixes src workspace
      - uv run ruff format src workspace
      - uv run black src workspace
    desc: "Auto-fix lint issues and format code"

  lint:
    cmds:
      - uv run ruff check src workspace
    desc: "Check code with ruff"

  mypy:
    cmds:
      - uv run mypy src --ignore-missing-imports --no-strict-optional
    desc: "Run type checking with mypy"
      
  mypy-strict:
    cmds:
      - uv run mypy src --strict
    desc: "Run strict type checking with mypy"

  check:
    cmds:
      - task: fmt
      - task: lint
      - task: mypy
    desc: "Run all fixes and checks"

  docs-serve:
    cmds:
      - uv run mkdocs serve
    desc: "Start local documentation server"

  docs-build:
    cmds:
      - uv run mkdocs build --clean
    desc: "Build documentation"

  docs-build-strict:
    cmds:
      - uv run mkdocs build --clean --strict
    desc: "Build documentation with strict mode"

  docs-deploy:
    cmds:
      - uv run mkdocs gh-deploy --force
    desc: "Deploy documentation to GitHub Pages"

  docs-clean:
    cmds:
      - rm -rf site/
    desc: "Clean built documentation"

  docs-gen:
    cmds:
      - uv run python docs/gen_experiment_docs.py
    desc: "Generate experiment documentation from source code"

  docs:
    cmds:
      - task: docs-build
      - task: docs-serve
    desc: "Build and serve documentation locally"
