version: '3'

tasks:
  fmt:
    cmds:
      - uv run ruff check --fix src workspace
      - uv run ruff check --fix --unsafe-fixes src workspace
      - uv run ruff format src workspace
      - uv run black src workspace
    desc: "Auto-fix lint issues and format code"

  lint:
    cmds:
      - uv run ruff check src workspace
    desc: "Check code with ruff"

  mypy:
    cmds:
      - uv run mypy src --ignore-missing-imports --no-strict-optional
    desc: "Run type checking with mypy"
      
  mypy-strict:
    cmds:
      - uv run mypy src workspace
    desc: "Run strict type checking with mypy"

  check:
    cmds:
      - task: fmt
      - task: lint
      - task: mypy
    desc: "Run all fixes and checks"
