name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Verify test setup
      run: |
        uv run python -c "import pytest; print(f'pytest version: {pytest.__version__}')"
        uv run python -c "import pytest_cov; print('pytest-cov available')"

    - name: Lint with ruff
      run: |
        uv run ruff check src/

    - name: Format check with ruff
      run: |
        uv run ruff format --check src/

    - name: Type check with mypy
      run: |
        uv run mypy src/ --ignore-missing-imports --no-strict-optional
      continue-on-error: true

    - name: Test with pytest
      run: |
        uv run python -m pytest tests/ -v --cov=src/oqtopus_experiments --cov-report=xml --cov-report=term-missing --cov-fail-under=30
      env:
        PYTHONPATH: src

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        # Token is optional for public repos
        token: ${{ secrets.CODECOV_TOKEN }}
      if: ${{ secrets.CODECOV_TOKEN != '' }}
